const ProjectData = [
    {
        id: 1,
        image: "image/Shopperia.png",
        name: " Shopperia(React Ecomm)",
        git: "https://github.com/shubhamkr83/Shopperia",
        live: "https://shopperia.netlify.app",
        category: "Full Stack",
    },
    {
        id: 4,
        image: "https://user-images.githubusercontent.com/72254047/244579533-56eb1756-df78-4285-b138-e216ee34b385.png",
        name: "Foodie",
        git: "https://github.com/shubhamkr83/Foodie-WebApp",
        live: "https://foodie-webapp.onrender.com",
        category: "Full Stack",
    },
    {
        id: 2,
        image: "https://user-images.githubusercontent.com/72254047/217277200-17580e08-46de-46ca-bf2a-8f7b4fbd1d50.png",
        name: "Moviemania",
        git: "https://github.com/shubhamkr83/Moviemania",
        live: "https://skmoviemania.netlify.app",
        category: "FrontEnd",
    },
    {
        id: 3,
        image: "https://user-images.githubusercontent.com/72254047/233765583-6683fdf9-9027-484a-b286-58065d8822a0.png",
        name: "React Todos",
        git: "https://github.com/shubhamkr83/react-todo",
        live: "https://react-todolist01.netlify.app",
        category: "FrontEnd",
    },
    {
        id: 5,
        image: "https://user-images.githubusercontent.com/72254047/221830231-789361ae-51a7-401a-8109-ca04e031095f.png",
        name: "Placement cell",
        git: "https://github.com/shubhamkr83/Placement-cell-app",
        live: "https://placementcell-h84y.onrender.com",
        category: "Full Stack",
    },
    {
        id: 7,
        image: "https://user-images.githubusercontent.com/72254047/243905261-7ba02639-ea57-468d-b7e9-3a3e095f756a.png",
        name: "React Chat App",
        git: "https://github.com/shubhamkr83/React_Chat_App",
        live: "https://reactchatapp01.netlify.app",
        category: "FrontEnd",
    },
    {
        id: 8,
        image: "https://user-images.githubusercontent.com/72254047/243904668-9c3bf331-421d-4a36-a58b-232037d11c4a.png",
        name: "Contact List Web App",
        git: "https://github.com/shubhamkr83/contactlistapp",
        live: "https://contactlistreactapp.netlify.app",
        category: "FrontEnd",
    },
    {
        id: 9,
        image: "https://user-images.githubusercontent.com/72254047/245164081-b56be2d6-2e3a-499f-96c7-dd6d4f1967c9.png",
        name: "Employee Review System",
        git: "https://github.com/shubhamkr83/Employee-Review-System",
        live: "https://ersystem-p85s.onrender.com",
        category: "Full Stack",
    },
    {
        id: 10,
        image: "https://user-images.githubusercontent.com/72254047/245163279-9f8bf2d9-1089-47b8-97c0-cd6f79b1f0f1.png",
        name: "Shopperia Web3",
        git: "https://github.com/shubhamkr83/Web3-Ecomm",
        live: "https://github.com/shubhamkr83/Web3-Ecomm",
        category: "Full Stack",
    },
    {
        id: 11,
        image: "image/Ecomm-webp.webp",
        name: "Ecommerce Web",
        git: "https://github.com/shubhamkr83/Ecom-website",
        live: "https://shubh-ecommerce.netlify.app",
        category: "FrontEnd",
    },
    {
        id: 6,
        image: "https://user-images.githubusercontent.com/72254047/247047204-23979487-8f7c-4c31-a57b-14b63b8b3fe3.png",
        name: "My Portfolio",
        git: "https://github.com/shubhamkr83/React-Vite-Portfolio",
        live: "https://shubhamweb.netlify.app",
        category: "FrontEnd",
    },

    // {
    //     id: 12,
    //     image1: "image/Carg-webp.webp",
    //     image2: "image/Carg-jpg.jpg",
    //     name: "Car Racing Game",
    //     link: "https://car-racing-game01.netlify.app/",
    //     category: "FrontEnd",
    // },
    // {
    //     id: 13,
    //     image1: "https://user-images.githubusercontent.com/72254047/217031437-b09fc265-58c0-4260-8457-5b282af2e17e.png",
    //     name: "Todo-App",
    //     link: "https://github.com/shubhamkr83/Todo-App",
    //     category: "FrontEnd",
    // },
    // {
    //     id: 14,
    //     image1: "image/Musam.png",
    //     name: "Awesome Musam App",
    //     link: "https://awesomemusam.herokuapp.com/",
    //     category: "FrontEnd",
    // },
    // {
    //     id: 15,
    //     image: "image/e-learn-min.jpg",
    //     name: "E-Learning",
    //     git: "https://shub-edu.netlify.app/",
    //     live: "https://shub-edu.netlify.app/",
    //     category: "FrontEnd",
    // },
    // {
    //     id: 16,
    //     image: "image/fitness-min.jpg",
    //     name: "Fitness",
    //     git: "https://shub-health.netlify.app/",
    //     live: "https://shub-health.netlify.app/",
    //     category: "FrontEnd",
    // },
    // {
    //     id: 17,
    //     image: "image/travels-min.jpg",
    //     name: "Tours & Travels",
    //     git: "https://shub-travels.netlify.app/",
    //     live: "https://shub-travels.netlify.app/",
    //     category: "FrontEnd",
    // },
];

export default ProjectData;